version: 2
updates:
  - package-ecosystem: "pip" 
    directory: "/" 
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "PT"
    pull-request-branch-name:
      separator: "-"
    labels:
      - "Dependabot"
    commit-message:
      prefix: "Version update"
      include: "scope"
    reviewers:
      - "jkusek98"
