name: CI for PyDREAM

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda create -y -q -n ci-environment -c conda-forge -c alubbock python=${{ matrix.python-version }} numpy scipy nose cython pysb
        conda init bash
    - name: Activate conda
      run: |
        conda activate ci-environment
        python -m pip install .
    - name: Test with pytest
      run: |
        nosetests
