name: CI for PyDREAM

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7","3.8","3.9"]
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Checkout Stage
      uses: actions/checkout@v3
    - name: Conda Setup
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: ci-env
        environment-file: environment.yml
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false
    - name: Install dependencies
      run: |
        python -m pip install .
    - name: Test with pytest
      run: |
        nosetests -v
